on:
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        version: [6.3.0, 5.5.1]

    runs-on: ${{ matrix.os }}
    steps:
      - run: wget https://cdn.geekbench.com/Geekbench-${{ matrix.version }}-Linux.tar.gz
      - run: tar --strip-components=1 -xf Geekbench-*-Linux.tar.gz
      - run: ./geekbench[0-9]
